name: CI

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "[0-9].[0-9].[0-9]b[0-9]"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install tox
        run: python -m pip install tox tox-gh-actions
      - name: Run tox
        run: python -m tox
      - uses: codecov/codecov-action@v1
  deploy:
    runs-on: ubuntu-latest
    needs:
      - tests
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pypa/build
        run: python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
